### PR TITLE
Added README for installation on Mac OS X

### PR DESCRIPTION
**Pull request by demc**
I was able to get this working on Mac OS X with some tweaks.

### CODE REVIEW

**Comment by demc** [comment]
Ping

**Comment by hawkerm** [comment]
Hey Derrick, this is amazing, thank you so much! We've long been awaiting the person with a Mac to have the patience to try this out. Would love to know more about how you found out about the project, and if you've been using it at all.

Sorry I haven't responded before now, I've been pretty swamped the last couple months, and I haven't had a chance to come back to the project yet (first time logging into GitHub even to see the notice).  I still need to package the official 1.2 release!

I feel like we need to link to your Mac readme in the [main readme](https://github.com/Mikeware/SpaceBattleArena/blob/master/README.md) and [documentation](https://github.com/Mikeware/SpaceBattleArena/blob/master/doc/server/setup.md) somewhere as well.  It'd also be good to just put this in the feat/srace branch as the next thing I do will be merging that back to the master, and I haven't made any changes to master since the branch.  Let me know your thoughts.

**Comment by colonelmac** [comment]
Hi Mike!

I saw this at the CSTA conference! I'll update the documentation when I get a few free cycles. 
Have you all considered porting the frontend to HTML5/JS so that it could be delivered via web?

Thanks!

**Comment by demc** [comment]
I saw this at the CSTA conference! I'll update this request when I get a few free cycles. 
Have you all considered moving the frontend to HTML5/JS so that the gameboard could be hosted?

**Comment by hawkerm** [comment]
I still have to get around to shipping 1.2 bits. I have thought about some ideas for v2, but haven't gotten there yet.

**Pull request merged**
